export { Home as default } from './Home' 
export { Profile as default } from './Profile' 
export { Payment as default } from './Payment' 
export { Transactions as default } from './Transactions' 
export { Expenses as default } from './CreateExpense' 